kafka:
  brokers:
    - redpanda:9092

schemaRegistry:
  enabled: true
  urls:
    - http://redpanda:8081

serde:
  protobuf:
    enabled: true
    mappings:
      - topicName: order.created
        valueProtoType: order.v1.Order
    fileSystem:
      enabled: true
      paths:
        - /proto
