kafka:
  brokers:
    - redpanda-1:9092
    - redpanda-2:9092
    - redpanda-3:9092

schemaRegistry:
  enabled: true
  urls:
    - http://redpanda-1:8081

serde:
  protobuf:
    enabled: true
    mappings:
      - topicName: order.created
        valueProtoType: order.v1.Order
    fileSystem:
      enabled: true
      paths:
        - /proto
