# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/v1/payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18payment/v1/payment.proto\x12\npayment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n\x07Payment\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12)\n\x06status\x18\x06 \x01(\x0e\x32\x19.payment.v1.PaymentStatus\x12\x11\n\tprocessor\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xbf\x01\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n\x19PAYMENT_STATUS_AUTHORIZED\x10\x02\x12\x1b\n\x17PAYMENT_STATUS_CAPTURED\x10\x03\x12\x19\n\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1b\n\x17PAYMENT_STATUS_REFUNDED\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.v1.payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYMENTSTATUS._serialized_start=289
  _PAYMENTSTATUS._serialized_end=480
  _PAYMENT._serialized_start=74
  _PAYMENT._serialized_end=286
# @@protoc_insertion_point(module_scope)
